### ISSUE TITLE
Get rid of dialogs popping up

### ISSUE THREAD

**Issue by AlexanderKnueppel** [AlexanderKnueppel/ContractIDE#1]
When a new component is created, a lot of dialogs are popping up:
![image](https://user-images.githubusercontent.com/263321/45475660-5747a000-b73d-11e8-82fe-0d38e427cf82.png)

It would be good to just create "dummy" components, which can be customized directly on the graphical representation.

**Comment by hfenske33** [comment]
![screenshot from 2018-09-18 10-54-20](https://user-images.githubusercontent.com/32099069/45676187-75dcdb00-bb31-11e8-979e-eedf4ac847f8.png)
This popup is also pretty useless. Main problem: its a mix of swing + swt
Suggestion: Dummy-Object directly modifieable in graphical representation + new tab with properties next to task (similar to ecore-modelling)
