### ISSUE TITLE
System block's line of separation remains unmodified after changing size

### ISSUE THREAD

**Issue by AlexanderKnueppel** [AlexanderKnueppel/ContractIDE#30]
![image](https://user-images.githubusercontent.com/263321/48932420-1d90d380-eefc-11e8-8529-227159aeb2de.png)

The behavior should be handled equally to all other blocks (i.e., line's length and block's width should conform).

**Comment by Sabrina1231** [comment]
identified the mistake in class ContractModellingFeatureProvider. Solved issue by adding "instanceof System" in if clause.
