### ISSUE TITLE
Context menu for projects

### ISSUE THREAD

**Issue by AlexanderKnueppel** [AlexanderKnueppel/ContractIDE#6]
Currently, there is an entry in the context menu with CCC -> Command.
Tasks to do:

* Rename **CCC** to **ContractIDE**
* **Command** can be renamed to **Export to CCC config. (.xml)**
* Add a unique icon to **ContractIDE**

**Comment by hfenske33** [comment]
For the time being I have created the following symbols (is also part of issue 3):
![cide2_64](https://user-images.githubusercontent.com/32099069/45642115-9ff1b700-bab7-11e8-9a57-f9189ccfd766.png)
![cide64](https://user-images.githubusercontent.com/32099069/45642116-a08a4d80-bab7-11e8-8f5a-a9b9b153097b.png)

**Comment by AlexanderKnueppel** [comment]
Closed by 18d1699
